[project]
name = "proxy-server"
version = "0.1.1"
description = "A simple proxy server implemented in Python."
readme = "README.md"
requires-python = ">=3.13,<=3.14"
license = { text = "MIT" }
dependencies = [
    "fastapi==0.141.1",
    "mysql-connector==2.2.9",
    "pydantic==2.13.5",
    "requests==2.34.2",
    "uvicorn==0.52.4",
]

[dependency-groups]
dev = [
    "ruff==0.16.5",
    "bandit==1.9.4",
    "pyright==1.1.411",
]

[tool.bandit]
exclude_dirs = [".venv"]
